name: Update create-vite

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/vitejs/vite.git

      - name: Fetch upstream main branch
        run: git fetch upstream main

      - name: Create and checkout update-create-vite branch
        run: git checkout -b update-create-vite upstream/main

      - name: Copy create-vite changes to starter repository
        run: |
          mkdir -p packages
          cp -r packages/create-vite/* packages/

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update create-vite from vitejs/vite repository"

      - name: Push changes to starter repository
        run: git push origin update-create-vite:main
