name: Update create-vite

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync create-vite changes from vitejs/vite repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git remote add upstream https://github.com/vitejs/vite.git
          git fetch upstream main
          git checkout -b update-create-vite upstream/main -- packages/create-vite
          git checkout main
          git merge update-create-vite --no-commit --no-ff
          git commit -m "Update create-vite from vitejs/vite repository"
          git push origin main
